### PR TITLE
# Remove redeclared consts & use swc (x10 times faster than terser)

### PR DESCRIPTION
**Pull request by erixweb**
# Changed
Added SWC which is x10 times faster than terser
Removed redeclared constants (Not sure if I've removed some constant that wasn't redeclared by mistake)

### CODE REVIEW

**Comment by erixweb** [comment]
I'd also like to know where did the Greenfrog's discord server go to?

**Comment by kotinash** [comment]
> I'd also like to know where did the Greenfrog's discord server go to?

deleted

**Comment by kotinash** [comment]
working on a new software

**Comment by erixweb** [comment]
> working on a new software

Ok, let me know when there's a discord server for it. 😄

**Pull request merged**
